"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

/**
 * Fetch today's reservations for a specific branch.
 */
export async function getTodayReservations(branchId: string) {
    try {
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        const tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1);

        const reservations = await prisma.reservation.findMany({
            where: {
                userId: branchId,
                date: {
                    gte: today,
                    lt: tomorrow,
                },
            },
            include: {
                promoter: true, // Includes RP details if generated by one
                table: true,
            },
            orderBy: {
                date: "asc",
            },
        });

        return { success: true, data: reservations };
    } catch (error) {
        console.error("Error fetching today's reservations:", error);
        return { success: false, error: "Failed to fetch reservations." };
    }
}

/**
 * Validates a scanned QR code.
 */
export async function scanReservationQR(qrData: string, currentBranchId: string) {
    try {
        const reservation = await prisma.reservation.findUnique({
            where: { id: qrData },
            include: {
                promoter: true,
            },
        });

        if (!reservation) {
            return { success: false, error: "Reservación no encontrada." };
        }

        if (reservation.userId !== currentBranchId) {
            return { success: false, error: "Este código de reservación no pertenece a esta sucursal." };
        }

        return { success: true, data: reservation };
    } catch (error) {
        console.error("Error scanning QR:", error);
        return { success: false, error: "Error al escanear el código QR." };
    }
}

/**
 * Updates a reservation's status and actual guests count.
 */
export async function updateReservationHostess(params: {
    reservationId: string;
    status: string;
    actualGuests?: number;
    adminId: string; // The user making the change (hostess/admin)
}) {
    try {
        const existing = await prisma.reservation.findUnique({
            where: { id: params.reservationId },
        });

        if (!existing) {
            return { success: false, error: "Reservación no encontrada." };
        }

        const updated = await prisma.reservation.update({
            where: { id: params.reservationId },
            data: {
                status: params.status,
                ...(params.actualGuests !== undefined && { actualGuests: params.actualGuests }),
            },
        });

        // Create an audit log for transparency
        if (params.actualGuests !== undefined && existing.actualGuests !== params.actualGuests) {
            await prisma.auditLog.create({
                data: {
                    adminId: params.adminId,
                    action: "UPDATE_RESERVATION_GUESTS",
                    entity: "RESERVATION",
                    entityId: params.reservationId,
                    details: {
                        oldValue: existing.actualGuests ?? existing.partySize, // fallback to partySize if null
                        newValue: params.actualGuests,
                    },
                },
            });
        }

        revalidatePath(`/hostess`);
        return { success: true, data: updated };
    } catch (error) {
        console.error("Error updating reservation:", error);
        return { success: false, error: "Failed to update reservation." };
    }
}

/**
 * Generates a CSV text string of today's reservations.
 */
export async function downloadDailyReservationsCSV(branchId: string) {
    try {
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1);

        const reservations = await prisma.reservation.findMany({
            where: {
                userId: branchId,
                date: { gte: today, lt: tomorrow },
            },
            include: { promoter: true },
            orderBy: { date: "asc" },
        });

        const headers = ["Hora", "Cliente", "Teléfono", "Reservados", "Reales", "RP", "Estado"];
        const rows = reservations.map(r => {
            const time = r.date.toLocaleTimeString("es-MX", { hour: '2-digit', minute: '2-digit' });
            return [
                time,
                `"${r.customerName}"`,
                r.customerPhone || "N/A",
                r.partySize,
                r.actualGuests || r.partySize,
                r.promoter ? `"${r.promoter.name}"` : "Directo",
                r.status,
            ].join(",");
        });

        const csvContent = [headers.join(","), ...rows].join("\n");
        return { success: true, csv: csvContent };
    } catch (error) {
        console.error("Error generating CSV:", error);
        return { success: false, error: "Failed to generate CSV." };
    }
}
