'use client'

import { useState, useEffect } from 'react'
import { Activity, ArrowRight, UserCheck, Utensils, Music, CheckCircle2, AlertTriangle, XCircle } from 'lucide-react'
import FeatureGuard from '@/components/common/FeatureGuard'
import { toast } from 'sonner'

interface PhaseData {
    id: string
    title: string
    score: number // 1 to 5
    icon: any
    description: string
}

export default function HeatmapWidget() {
    const [journey, setJourney] = useState<PhaseData[]>([])
    const [isLoading, setIsLoading] = useState(true)

    useEffect(() => {
        fetchHeatmapData()
    }, [])

    const fetchHeatmapData = async () => {
        setIsLoading(true)
        try {
            // Re-using the reputation extraction endpoint or creating a dedicated one
            // We'll mock the extraction here temporarily until we wire a specific DB query,
            // but ideally this is generated by Gemini or maps to the `ReputationScore` table 
            // since we already extract Food, Ambiance, Service, Speed, etc.

            // For now let's hit our reputation endpoint to get the latest DB score
            const res = await fetch('/api/ai/reputation-history?limit=1')
            if (res.ok) {
                const data = await res.json()
                if (data && data.length > 0) {
                    const latest = data[0]
                    setJourney([
                        { id: 'arrival', title: 'Llegada & Recepción', score: latest.speedScore || 4.5, icon: UserCheck, description: 'Tiempo de espera y bienvenida' },
                        { id: 'service', title: 'Servicio en Mesa', score: latest.serviceScore || 4.2, icon: Activity, description: 'Atención del mesero y actitud' },
                        { id: 'food', title: 'Calidad de Alimentos', score: latest.foodScore || 4.8, icon: Utensils, description: 'Sabor, temperatura y presentación' },
                        { id: 'ambiance', title: 'Ambiente & Limpieza', score: latest.ambianceScore || 3.5, icon: Music, description: 'Música, clima, aseo general' },
                    ])
                } else {
                    setJourney(getEmptyJourney())
                }
            } else {
                setJourney(getEmptyJourney())
            }
        } catch (error) {
            console.error(error)
            setJourney(getEmptyJourney())
        } finally {
            setIsLoading(false)
        }
    }

    const getEmptyJourney = () => [
        { id: 'arrival', title: 'Llegada & Recepción', score: 0, icon: UserCheck, description: 'Tiempo de espera y bienvenida' },
        { id: 'service', title: 'Servicio en Mesa', score: 0, icon: Activity, description: 'Atención del mesero y actitud' },
        { id: 'food', title: 'Calidad de Alimentos', score: 0, icon: Utensils, description: 'Sabor, temperatura y presentación' },
        { id: 'ambiance', title: 'Ambiente & Limpieza', score: 0, icon: Music, description: 'Música, clima, aseo general' },
    ]

    const getStatusDetails = (score: number) => {
        if (score === 0) return { color: 'bg-gray-800 border-gray-700 text-gray-500', icon: null, text: 'text-gray-500' }
        if (score >= 4.5) return { color: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400', icon: <CheckCircle2 className="w-4 h-4 text-emerald-500" />, text: 'text-emerald-400' }
        if (score >= 3.5) return { color: 'bg-amber-500/10 border-amber-500/30 text-amber-400', icon: <AlertTriangle className="w-4 h-4 text-amber-500" />, text: 'text-amber-400' }
        return { color: 'bg-red-500/10 border-red-500/30 text-red-500', icon: <XCircle className="w-4 h-4 text-red-500" />, text: 'text-red-500' }
    }

    return (
        <FeatureGuard feature="ai_analytics">
            <div className="flex flex-col h-full rounded-3xl bg-[#0F0F0F] border border-white/5 overflow-hidden shadow-2xl transition-all p-6">

                <div className="mb-6">
                    <h3 className="text-xl font-bold flex items-center gap-2 text-white">
                        <Activity className="w-5 h-5 text-indigo-400" />
                        Mapa de Calor de Experiencia
                    </h3>
                    <p className="text-sm text-gray-500 mt-1">
                        Identifica los cuellos de botella operativos a lo largo del recorrido del cliente.
                    </p>
                </div>

                <div className="flex-1 flex flex-col md:flex-row justify-between items-center relative py-8 px-4">

                    {/* Connecting Line Backdrop */}
                    <div className="absolute top-1/2 left-10 right-10 h-1 bg-white/5 -translate-y-1/2 hidden md:block rounded-full z-0"></div>

                    {isLoading ? (
                        <div className="w-full flex justify-center"><div className="animate-pulse h-8 w-32 bg-white/10 rounded-full"></div></div>
                    ) : (
                        journey.map((phase, index) => {
                            const status = getStatusDetails(phase.score)
                            const Icon = phase.icon
                            return (
                                <div key={phase.id} className="relative z-10 flex flex-col items-center group w-full md:w-1/4 mb-8 md:mb-0">

                                    {/* Score Bubble */}
                                    <div className={`w-16 h-16 rounded-2xl flex items-center justify-center border-2 shadow-xl mb-4 transition-transform group-hover:scale-110 ${status.color} bg-[#151515]`}>
                                        {phase.score > 0 ? (
                                            <span className="text-xl font-black">{phase.score.toFixed(1)}</span>
                                        ) : (
                                            <Icon className="w-6 h-6 opacity-30" />
                                        )}
                                    </div>

                                    {/* Text Info */}
                                    <div className="text-center">
                                        <h4 className="font-bold text-white text-sm mb-1">{phase.title}</h4>
                                        <p className="text-xs text-gray-500 px-4 h-8">{phase.description}</p>
                                    </div>

                                    {/* Status Indicator */}
                                    {phase.score > 0 && (
                                        <div className={`mt-3 flex items-center gap-1 text-xs font-bold ${status.text} bg-[#1A1A1A] px-3 py-1 rounded-full border border-white/5`}>
                                            {status.icon}
                                            {phase.score >= 4.5 ? 'Óptimo' : phase.score >= 3.5 ? 'Atención' : 'Crítico'}
                                        </div>
                                    )}

                                    {/* Arrow to Next (Mobile) */}
                                    {index < journey.length - 1 && (
                                        <ArrowRight className="w-5 h-5 text-white/10 md:hidden mt-6" />
                                    )}
                                </div>
                            )
                        })
                    )}
                </div>
            </div>
        </FeatureGuard>
    )
}
