'use client'

import { useState, useEffect } from 'react'
import { Activity, ArrowRight, UserCheck, Utensils, Music, CheckCircle2, AlertTriangle, XCircle, Info, Sparkles, X } from 'lucide-react'
import FeatureGuard from '@/components/common/FeatureGuard'
import { toast } from 'sonner'
import { useDashboard } from '@/context/DashboardContext'
import { AnimatePresence, motion } from 'framer-motion'

interface PhaseData {
    id: string
    title: string
    score: number // 1 to 5
    icon: any
    description: string
}

export default function HeatmapWidget() {
    const { branchId } = useDashboard()
    const [journey, setJourney] = useState<PhaseData[]>([])
    const [isLoading, setIsLoading] = useState(true)
    const [showInfo, setShowInfo] = useState(false)

    useEffect(() => {
        fetchHeatmapData()
    }, [branchId])

    const fetchHeatmapData = async () => {
        setIsLoading(true)
        try {
            // Re-using the reputation extraction endpoint or creating a dedicated one
            // We'll mock the extraction here temporarily until we wire a specific DB query,
            // but ideally this is generated by Gemini or maps to the `ReputationScore` table 
            // since we already extract Food, Ambiance, Service, Speed, etc.

            // We'll hit our reputation endpoint to get the latest DB score, passing branchId if any.
            const url = branchId
                ? `/api/ai/reputation?limit=1&branchSlug=${branchId}`
                : `/api/ai/reputation?limit=1`

            const res = await fetch(url)
            if (res.ok) {
                const data = await res.json()
                if (data && data.length > 0) {
                    const latest = data[0]
                    setJourney([
                        { id: 'arrival', title: 'Llegada & Recepción', score: latest.speedScore || 4.5, icon: UserCheck, description: 'Tiempo de espera y bienvenida' },
                        { id: 'service', title: 'Servicio en Mesa', score: latest.serviceScore || 4.2, icon: Activity, description: 'Atención del mesero y actitud' },
                        { id: 'food', title: 'Calidad de Alimentos', score: latest.foodScore || 4.8, icon: Utensils, description: 'Sabor, temperatura y presentación' },
                        { id: 'ambiance', title: 'Ambiente & Limpieza', score: latest.ambianceScore || 3.5, icon: Music, description: 'Música, clima, aseo general' },
                    ])
                } else {
                    setJourney(getEmptyJourney())
                }
            } else {
                setJourney(getEmptyJourney())
            }
        } catch (error) {
            console.error(error)
            setJourney(getEmptyJourney())
        } finally {
            setIsLoading(false)
        }
    }

    const getEmptyJourney = () => [
        { id: 'arrival', title: 'Llegada & Recepción', score: 0, icon: UserCheck, description: 'Tiempo de espera y bienvenida' },
        { id: 'service', title: 'Servicio en Mesa', score: 0, icon: Activity, description: 'Atención del mesero y actitud' },
        { id: 'food', title: 'Calidad de Alimentos', score: 0, icon: Utensils, description: 'Sabor, temperatura y presentación' },
        { id: 'ambiance', title: 'Ambiente & Limpieza', score: 0, icon: Music, description: 'Música, clima, aseo general' },
    ]

    const getStatusDetails = (score: number) => {
        if (score === 0) return { color: 'bg-gray-800 border-gray-700 text-gray-500', icon: null, text: 'text-gray-500' }
        if (score >= 4.5) return { color: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400', icon: <CheckCircle2 className="w-4 h-4 text-emerald-500" />, text: 'text-emerald-400' }
        if (score >= 3.5) return { color: 'bg-amber-500/10 border-amber-500/30 text-amber-400', icon: <AlertTriangle className="w-4 h-4 text-amber-500" />, text: 'text-amber-400' }
        return { color: 'bg-red-500/10 border-red-500/30 text-red-500', icon: <XCircle className="w-4 h-4 text-red-500" />, text: 'text-red-500' }
    }

    return (
        <FeatureGuard feature="ai_analytics">
            <div className="flex flex-col h-full rounded-3xl bg-[#0F0F0F] border border-white/5 overflow-hidden shadow-2xl transition-all p-6">

                <div className="mb-6 flex items-start justify-between">
                    <div>
                        <h3 className="text-xl font-bold flex items-center gap-2 text-white">
                            <Activity className="w-5 h-5 text-indigo-400" />
                            Mapa de Calor de Experiencia
                        </h3>
                        <p className="text-sm text-gray-500 mt-1">
                            Identifica los cuellos de botella operativos a lo largo del recorrido del cliente.
                        </p>
                    </div>
                    <button
                        onClick={() => setShowInfo(true)}
                        className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition group/btn relative shrink-0"
                        title="¿Cómo funciona?"
                    >
                        <Info className="w-4 h-4 text-indigo-400" />
                        <span className="absolute -top-8 right-0 bg-black text-xs px-2 py-1 rounded opacity-0 group-hover/btn:opacity-100 transition whitespace-nowrap pointer-events-none z-50">
                            ¿Cómo funciona?
                        </span>
                    </button>
                </div>

                <div className="flex-1 overflow-x-auto hide-scrollbar snap-x snap-mandatory pb-4 md:pb-0">
                    <div className="flex flex-row md:justify-between items-start relative py-8 px-2 gap-4 md:gap-4 lg:gap-8 min-w-max md:min-w-0 w-full">
                        {/* Connecting Line Backdrop */}
                        <div className="absolute top-1/2 left-10 right-10 h-1 bg-white/5 -translate-y-1/2 hidden md:block rounded-full z-0"></div>

                        {isLoading ? (
                            <div className="w-full flex justify-center"><div className="animate-pulse h-8 w-32 bg-white/10 rounded-full"></div></div>
                        ) : (
                            journey.map((phase, index) => {
                                const status = getStatusDetails(phase.score)
                                const Icon = phase.icon
                                return (
                                    <div key={phase.id} className="relative z-10 flex flex-col items-center group w-[160px] md:flex-1 shrink-0 snap-center md:snap-none px-2">

                                        {/* Score Bubble */}
                                        <div className={`w-16 h-16 rounded-2xl flex items-center justify-center border-2 shadow-xl mb-4 transition-transform group-hover:scale-110 ${phase.score > 0 ? getStatusDetails(phase.score).color : 'bg-gray-800/80 border-gray-700/50 text-gray-500'} bg-[#151515] shrink-0`}>
                                            {phase.score > 0 ? (
                                                <span className="text-xl font-black">{phase.score.toFixed(1)}</span>
                                            ) : (
                                                <Icon className="w-6 h-6 opacity-30" />
                                            )}
                                        </div>

                                        {/* Text Info */}
                                        <div className="text-center w-full">
                                            <h4 className="font-bold text-white text-sm mb-1.5 leading-tight text-balance">{phase.title}</h4>
                                            <p className="text-xs text-gray-500 leading-snug min-h-[40px] text-balance">{phase.description}</p>
                                        </div>

                                        {/* Status Indicator */}
                                        {phase.score > 0 && (
                                            <div className={`mt-3 flex items-center gap-1 text-[10px] md:text-xs font-bold ${getStatusDetails(phase.score).text} bg-[#1A1A1A] px-3 py-1 rounded-full border border-white/5`}>
                                                {getStatusDetails(phase.score).icon}
                                                {phase.score >= 4.5 ? 'Óptimo' : phase.score >= 3.5 ? 'Atención' : 'Crítico'}
                                            </div>
                                        )}

                                        {/* Arrow to Next (Mobile) */}
                                        {index < journey.length - 1 && (
                                            <ArrowRight className="w-5 h-5 text-white/10 md:hidden mt-6" />
                                        )}
                                    </div>
                                )
                            })
                        )}
                    </div>
                </div>
            </div>

            {/* AI Explanation Modal */}
            <AnimatePresence>
                {showInfo && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
                        onClick={() => setShowInfo(false)}
                    >
                        <motion.div
                            initial={{ scale: 0.95, y: 10 }}
                            animate={{ scale: 1, y: 0 }}
                            exit={{ scale: 0.95, y: 10 }}
                            onClick={(e) => e.stopPropagation()}
                            className="bg-[#111] border border-white/10 rounded-3xl p-6 max-w-md w-full shadow-2xl overflow-y-auto max-h-[85vh] custom-scrollbar"
                        >
                            <div className="flex justify-between items-start mb-6">
                                <h3 className="text-xl font-bold flex items-center gap-2 text-white">
                                    <Sparkles className="w-6 h-6 text-indigo-400" />
                                    ¿Cómo funciona la IA?
                                </h3>
                                <button onClick={() => setShowInfo(false)} className="p-2 rounded-full hover:bg-white/10 text-gray-400 transition">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>

                            <div className="space-y-4 text-sm text-gray-300 leading-relaxed">
                                <p>
                                    El <strong className="text-amber-400">Mapa de Calor</strong> segmenta la experiencia de tu cliente en 4 fases críticas para identificar exactamente en qué punto operativo estás fallando o sobresaliendo.
                                </p>

                                <ul className="space-y-3 bg-white/5 rounded-xl p-4 border border-white/5">
                                    <li><strong className="text-white">Detección de Fases:</strong> La IA clasifica miles de comentarios en: <i>(1) Llegada, (2) Servicio, (3) Comida, y (4) Ambiente</i>.</li>
                                    <li><strong className="text-white">Puntuación:</strong> Asigna una calificación de 0 a 5 a cada fase basal a los sentimientos extraídos.</li>
                                    <li><strong className="text-white">Alerta Visual:</strong> Te colorea en <strong className="text-emerald-400">Verde</strong> lo que haces excelente, en <strong className="text-amber-400">Amarillo</strong> lo que requiere atención y en <strong className="text-red-500">Rojo</strong> los focos críticos que están ahuyentando clientes.</li>
                                </ul>
                            </div>

                            <button onClick={() => setShowInfo(false)} className="w-full py-3 mt-6 bg-white/10 hover:bg-white/20 text-white font-bold rounded-xl transition">
                                Entendido
                            </button>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>

        </FeatureGuard>
    )
}
