import { prisma } from '@/lib/prisma'
import { auth } from '@clerk/nextjs/server'

async function main() {
    console.log('Checking notifications...')
    // We can't easily get the 'current' user ID in a script without auth context, 
    // so we'll list ALL notifications to see if ANY exist.
    const count = await prisma.notification.count()
    console.log(`Total notifications in DB: ${count}`)

    if (count > 0) {
        const list = await prisma.notification.findMany({ take: 5 })
        console.log('Sample notifications:', JSON.stringify(list, null, 2))
    } else {
        // Determine a user to create a test notification for
        // Just find the first admin/user
        const user = await prisma.userSettings.findFirst()
        if (user) {
            console.log(`Creating test notification for user: ${user.userId}`)
            await prisma.notification.create({
                data: {
                    userId: user.userId,
                    type: 'SYSTEM',
                    title: 'Test Notification Script',
                    message: 'This is a test notification generated by the script.',
                    isRead: false
                }
            })
            console.log('Test notification created. Check the dashboard.')
        } else {
            console.log('No users found to create a test notification for.')
        }
    }
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
