import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    let userId = process.argv[2]
    if (!userId) {
        const user = await prisma.userSettings.findFirst()
        if (user) {
            console.log(`No userId provided. Using first found user: ${user.user_id || user.userId}`)
            userId = user.userId
        } else {
            console.error('No userId provided and no users found in DB.')
            process.exit(1)
        }
    }

    console.log(`Filling survey limit for user: ${userId}`)

    // Get current count
    const count = await prisma.survey.count({ where: { userId } })
    console.log(`Current surveys: ${count}`)

    const target = 3 // Assuming free/power limit is low.
    const toCreate = Math.max(0, target - count)

    if (toCreate === 0) {
        console.log('Already at or above limit (assuming 3).')
        return
    }

    console.log(`Creating ${toCreate} dummy surveys...`)

    for (let i = 0; i < toCreate; i++) {
        await prisma.survey.create({
            data: {
                userId,
                title: `Dummy Survey ${count + i + 1}`,
                description: 'Autogenerated for testing limits',
                isActive: true,
                type: 'SATISFACTION',
                questions: {
                    create: [
                        { type: 'RATING', text: 'Califica tu experiencia', order: 0 }
                    ]
                }
            }
        })
    }

    console.log('✅ Done! Limit should be reached.')
}

main()
    .catch(e => console.error(e))
    .finally(async () => await prisma.$disconnect())
